### PR TITLE
Fix the CI and remove deprecated python interpreter and django versions

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
@carlio I've been working on this on the side, it's not ready yet but do you agree with the removal of python interpreters and django versions ? I don't know what the exact issue is buy my intuition is that we have a combination of two things:
- tox output is not easy to debug so launching things directly in the github action instead of tox could help with debug
- There might be incompatibilities between some elements of the test matrices (django 4.2 not available in python 3.8, that kind of things), so changing to a more hard coded approach might help remove them
What do you think ?

Refs #376

### CODE REVIEW

**Comment by carlio** [comment]
@Pierre-Sassoulas in order to avoid us working on the same thing, I plan to tackle this (and #376 and #405) this weekend.

**Comment by Pierre-Sassoulas** [comment]
Sure, I'm not touching this branch then 😄 Don't hesitate to ping me if I can do something to help

**Comment by Pierre-Sassoulas** [comment]
I could maybe open another MR to merge [Move pylint config out of tox](https://github.com/pylint-dev/pylint-django/pull/400/commits/096c15d59caadf3049280814d4e0655beae4a0bb)

**Comment by carlio** [comment]
@Pierre-Sassoulas I have been trying to fix the CI pipeline but I think that tox+poetry and all the different versions of python and django are not playing well together. Some combinations install the dev dependencies (pytest, specifically) and some to not.

I've spent a while trying to debug it, but I think it's to do with version conflicts and how tox decides how to install from poetry deps.

Anyway, it's a bit of a mess - see all my attempts in the list of actions!). I think I will rewrite the CI/packaging from zero and start fresh, and do that in combination with a new release removing some of the support for older dependencies.

**Comment by Pierre-Sassoulas** [comment]
Sounds good ! Might be the perfect occasion to fully migrate to pyproject.toml. Do you want me to do it ? (I have a commit ready moving pylint out of tox). Also I don't need a deep understanding of pylint-django to do that.

**Comment by carlio** [comment]
@Pierre-Sassoulas sure, although I am thinking that moving back to setuptools/setup.py for packaging might solve a lot of problems. Having all the config in the pyproject.toml makes sense in either case.

**Comment by carlio** [comment]
@Pierre-Sassoulas I finally closed #376 and the CI works now, so feel free to move ahead with the changes you wanted to make.

It's not completely cleanly fixed (there's a TODO in the test.sh) but at least for now it works.

**Comment by Pierre-Sassoulas** [comment]
Wow, amazing ! I opened #412, so I'm closing this :)

**Pull request closed without merging**
